liquibase:
  build:
    context: .    # Project root as build context
    dockerfile: liquibase/Dockerfile
  container_name: sample_liquibase
  depends_on:
    - postgres
  environment:
    LIQUIBASE_URL: jdbc:postgresql://postgres:5432/sampledb
    LIQUIBASE_USERNAME: postgres
    LIQUIBASE_PASSWORD: postgres
  volumes:
    - ./sampel:/liquibase/sampel  # optional for dev
