# syntax=docker/dockerfile:1
   
# Build stage  
FROM node:22 AS build

# Copy files
WORKDIR /app
COPY app/ .

# Install packages
RUN npm install
RUN npm run-script build

# Final stage
FROM nginx:stable as deploy
WORKDIR /usr/share/nginx/html
COPY --from=build /app/dist/ .
COPY --from=build /app/build.json .
COPY nginx.conf.dev /etc/nginx/conf.d/default.conf

EXPOSE 3000