name: Liquibase Run

on:
  push:
    branches:
      - main

jobs:
  run-liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Debug files
        run: |
          pwd
          ls -la
      - name: Build and start containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for Postgres
        run: |
          sleep 15
          docker ps

      - name: Debug Liquibase files
        run: |
          docker exec sample_liquibase ls -l /liquibase
          docker exec sample_liquibase ls -l /liquibase/sampel

      - name: Verify Postgres tables
        run: |
          docker exec sample_postgres psql -U postgres -d sampledb -c "\dt"
          docker exec sample_postgres psql -U postgres -d sampledb -c "SELECT COUNT(*) FROM users;"

      - name: Show Liquibase logs
        run: docker logs sample_liquibase

      - name: Tear down
        run: docker compose down
