name: Liquibase Run

on:
  push:
    branches:
      - main

jobs:
  run-liquibase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Go to project root and start containers
        run: |
          cd project-root
          docker compose up -d --build

      - name: Wait for DB
        run: sleep 15

      - name: Verify Liquibase files
        run: |
          docker exec sample_liquibase ls -l /liquibase/sample

      - name: Verify Postgres tables
        run: |
          docker exec sample_postgres psql -U postgres -d sampledb -c "\dt"

      - name: Tear down
        run: |
          cd project-root
          docker compose down
